# -*- coding: latin-1 -*-
#source: http://www.lokaltermin.eu/stoll-zitate
stoll_quotes = [
    #Physik, Mathematik, Philosophie
    "Licht ist keine Grenzgeschwindigkeit, vorsicht. Skalarwellen und stehende Welle hat ein vielfaches mehr.",
    "Auf die Maßeinheiten der Kernphysik hab ich bewusst verzichtet, denn außer mir würde das kaum jemand begreifen.",
    "Primzahlen bis 1024 werden in der Computertechnik benutzt.",
    "Darwin, Jude... klar. Da wurde die Biologie versaut – Einstein, Jude... die Physik wurde versaut, so kann ich das ganze Gebäude durchgehen.",
    "Die Wurzel aus -1 ist lösbar.",
    "Wurzelrechnung... lächerlich.",
    "Geht mal in eine kalte Fusion.",
    "Die Erde ist ein lebender Organismus.",
    "Es gibt einen energetischen Frühling.",
    "Es gibt auch keine Missing Links. (…) Alles ein Schwachsinn!",
    "Wir haben mit Braunsgas gearbeitet.",
    "Wir haben Blei verwandelt in Gold und Silber, Platin.",
    "Physik – 2/3 Schrott.",
    "Ich bin auch ein Anhänger der Kataklysmen-Theorie.",
    "Es gibt Evolution heißt AUS-wicklung, alles schon da gewesen.",
    "Klaus Böhme, das ist derjenige, der hocheffiziente BHKWs (...) baut, mittels Braunsgas, also kalte Fusion.",
    "Im Gegensatz zur Involution – EIN-wicklung. Ha! Physik, Physik... hä!",
    "Es handelt sich demnach um einen deutlichen und jederzeit reproduzierbaren Beweis für Homöopathie.",
    "Die Zahl 12 - auch ne kosmische Zahl.",
    "Angewandte MaTHEMAtik!",
    "Quarz als Skalarwelleninterferometer.",
    "Aber Vorsicht bei der Numerologie!",
    "Merkt ihr die Korrelation? Nachdenken!",
    "Man muss das dazu auch mal philosophisch betrachten.",
    "Aber steigtert euch nicht zu tief hinein - ich denke da an die Zahl 23 und was es alles gibt.",
    "Skalarwellen knallen quer Kontinente und Ozeane.",
    "Die jetzige elektromagnetische Theorie, wie sie an Schulen und Universitäten vertreten wird, ist falsch.",
    "Mit Überlichtgeschwindigkeit, ich betone: ÜBERLICHTGESCHWINDIGKEIT!",
    "Wer kennt die Maxwell'schen Gleichungen?",
    "Was sind die Pyramiden, wer weiß das? Schlüssel der Energie!",
    "Magnetohydrodynamik!",
    "Wir leben in einer Welt von Schwingungen, sprich Frequenzen, und damit korrelierender Wirbelmechanismen.",
    "Alles ist nur Bewegung oder Geschwindigkeit oder Schwingung.",
    "Mt diesem Braungas haben wir auch Elementtransmutationen vollbracht, allerdings machen wir das jetzt eleganter, mit einer Art Kaltlaser.",
    "Das ist eine Aufkraft!",
    "Weisste was die Primzahlen bedeuten? Einen Torus - raum-zeitlich gesehen.",
    "Alles nur störende Mikrowellen.",
    "Gemeint ist das organische Germanium 32.",
    "Physik, Mathematik, Philosophie.",
    "Wir Physiker sprechen vom sogenannten Dirac-Meer.",
    "Die muss man anzapfen entsprechend einem Implusions-Strudel.",
    "Sie ist ein Perpetuum Mobile!",
    "Das heißt eine logarithmische Spirale raum-zeitlich betrachtet nach Innen.",
    "Das nennt man KALTE FUSION!",
    "Es gibt nur Expansionsstrudel und Implosionsstrudel.",
    "Mikrowelle, Skalarwelle!",
    "Es gibt keine feste Materie - das ist ein Trugschluss.",
    "Mann muss immer den Ursprung erkennen - den Algorithmus, meine Damen, meine Herren.",
    "Die Natur braucht Wirbel.",
    "Mathematik ist die Sprache des Universums, der Intelligenz und erspart mir 1000 Seiten zu lesen.",
    "Man steckt erst richtig drin im Wissen, wenn man auch einer Klofrau das Raum/Zeit-Gefüge erklären kann.",
    "Das ist eine stehende Welle, die ist sofort da.",
    "Der Mensch ist eine energetische Matrix!",
    "Magie ist Physik durch Wollen!",
    "Meine Name ist Stoll, ich bin promovierter Naturwissenschaftler.",
    "Ich befasse mich mit freier Energie.",
    "Implosionstechnologie!",
    "Biologie ist Physik.",
    "Das ist kein Science Fiction!",
    "So einfach ist das, wenn man um die neue Physik weiß!",
    "Ich kann auch radioaktive Strahlung neutralisieren!",
    "Es gibt nur energetische Felder.",

    #Stuff we had previously
    "Allerdings muss ich gleich sagen: Bei mir beginnt die Mathematik, Physik und auch Geologie dort, wo das Hochschulstudium aufhört.",
    "Medizin ist Mathematik, Biologie ist Physik!",
    "Magie ist Physik durch Wollen!",
    "Der Mensch ist eine energetische Matrix.",
    "Der menschliche Zellkern ist gleich pures Licht, sprich: schwarze Sonnen.",
    "Wenn ein Mensch autogen sein Kraftfeld verstärkt, könnte er im Extremfall schweben. Also levitieren.",
    "Die Sonne ist KALT, da staunt ihr, wa?",
    "Wer weiß das? ... Wieder keiner!",
    "Im Prinzip brauchen wir nur drei Wissenschaften, um alles zu beschreiben: Physik. Mathematik. Philosophie.",
    "Und die Russen sind ja Waffentechnisch den Amerikanern weit überlegen. MUSS MAN WISSEN!",
    "...und das ist auch die Maschine, die entscheidend ist für Freie-Energie-Maschinen. Die muss man anzapfen entsprechend einem Implosions-Strudel. Das heißt, eine logarithmische Spirale raum-zeitlich betrachtet nach INNEN.",
    "Es gibt keine Zufälle, Das Wort 'Zufall' ist aus meinem Wortschatz gestrichen",
    "96 Flugzeuge * 60 Minuten * 14 Stunden * 40 Passagiere ergibt: 3.225.600 Passagiere pro Tag. PRO TAG! Das ist kein Science Fiction.",
    "Das hier ist nichts anderes als ein Strafplanet",
    "Der Selbsterhaltungstrieb der Zelle. Zur Erinnerung: [Die Zelle] ist ein Perpetuum Mobile, wie das Universum auch, ist ja klar.",
    "Wiederholung ist die Mutter der Weisheit",
    "Seit 10 Jahren wird der T-92 hergestellt. Ein modernster Panzer, russische Panzer mit Spitzengeschwindigkeit von 300 km/h",
    "Nukleare Strahlung lässt sich neutralisieren",
    "Magie ist Physik durch Volt",
    "Nikolai Tesla ist innerhalb von 5 Stunden mit deutschen Physikern zum Pluto geflogen um Gesteinsproben zu sammeln",
    "Man sollte mal Mikrowellenstrahler gegen die Love Parade einsetzen",
    "Es existiert keine Materie so wie diese beschrieben wird. Es existiert nur Bewegung oder Geschwindigkeit oder Schwingungen.",
    "Internet ist scheiße, da geh ich nicht rein",
    "Es existiert keine Materie, so wie diese gesehen und beschrieben wird, denn wir leben in einer Welt der Schwingungen und Frequenzen, also korrelierender Wirbelmechanismen",
    "Im Prinzip kann man sogar soweit abstrahieren: 'Alles ist nur Bewegung, Geschwindigkeit oder Schwingungen'",
    "Bindekräfte, welche die Materie zusammenhalten, sind Wirbel bzw. Strudel, inklusive ihrer Ein- und Auswirbelungen",
    "Die Formel E = mc² ist in dieser Form falsch bzw. wird zumindest falsch verstanden!",
    "Die reinste aller Energieformen, das Licht, ist ein Element es Jenseitsraumes, auch wenn es in die materielle Welt hineinwirkt.",
    "Die Zeit ist gekommen, da die Menschheit darüber bescheid wissen muss, was einige Wenige -- aus niederen Beweggründen -- seit sehr langer Zeit verschweigen.",
    "Das Wort 'Kosmos' bedeutet ja zu deutsch letztlich auch nichts anderes als: Ordnung.",
    "Tachyoneutrinos beinhalten den Terminus Tachyon(en) und Neutrino(s). Ersterer enthält die wichtige limitierende physikalische Größe Zeit und Geschwindigkeit (=Bewegung) und letzterer einen 'Schwingungs-Frequenz-Wirbelquant'!",
    "Ein Atom z.B. ähnelt nicht nur einer Sprungfeder, sondern es verfügt auch über ähnliche Eigenschaften, außer dass es mit hoher Geschwindigkeit rotiert.",
    "Dieses Gebilde kennen wir nur als sogenanntes 'Schwarzes Loch'! So, wie aber beispielsweise Luzifer nicht der Teufel, sondern der Lichtbringer ist (lux = das Licht), so ist 'unser' Jenseits-Raum (Τ-freier Raum) pures Licht!!",
    "Eine große ΦM-Dichte führt der menschlichen Zelle soviel Energie zu, dass er nur langsam altert.",
    "Wie im ... beschrieben, so ist die Zeit (T) physikalisch nichts weiter als universale Dichte in Korrelation mit der Raumbewegung.",
    "Implosions- und Expansionsstrudel sind zwar miteinander korrelierend, verfügen aber über eine unterschiedliche energetische Struktur.",
    "Unser Universum ist das klassische 'Perpetuum Mobile' weil es aus sich selbst heruas existiert bzw. lebt.",
    "Da unser Universum ein ewig existierendes Zirkulationssystem darstellt, findet der sogenannte Urknall jederzeit statt.",
    "Die Masse eines Körpers entspricht dem Gesamt-Volumen seiner Atomkerne, also dem Gesamt-Volumen seiner 'Mini-Schwarzen Löcher'.",
    "Sein spezifisches Gewicht ist das Verhältnis des Volumens seiner 'Mini-Schwarzen Löcher' zu seinem Gesamtvolumen bei einer bestimmten Temperatur und relativ zu Wasser.",
    "Wie erwähnt, steckt in τ ein rechtsrotierender (zum jeweiligen imaginären Mittelpunkt zielender), spiralförmiger Kraftverlauf.",
    "Die kleinen τ-freien Räume (die Atomkerne) erscheinen uns allgemein nur dann als Licht, wenn ihre Atome entbunden werden bzw. sich zerlegen.",
    "Zu beachten ist, dass wir in einer virtuellen Scheinwelt leben. Das bedeutet, dass wir nur die entsprechende Dichte der Schwingungen (Frequenzen) als unterschiedliche Aggregatzustände wahrnehmen!",
    "Strom ist nichts weiter als ausgeschiedene bzw. überschüssige Geschwindigkeit.",
    "Das Mini-Magnetfeld eines Atoms ist nichts weiter als sein Spin, der auch von τ weiter transportiert wird! Damit ist ein Magnet eine τ-Umwälzpumpe bzw. der Nachbau unseres Universums!",

    # Weltall, Galaxien und Dritte Macht
    "So sind Höhen ohne Tiefen nicht denkbar – siehe hermetisches Gesetz des Universums.",
    "Entscheidend ist die Länge des Frauenhaares als Sender und Empfänger.",
    "Aber das Frauenhaar, das müssen Sie begreifen, ist magnetisch, das hat ein anderes Magnetfeld.",
    "Ich denke an die Vril-Damen – transmediale Kontakte zum Aldebaran.",
    "Wir hatten den ersten Videorekorder der Welt.",
    "Die schwarze Macht – da geht es um Templerwissen und um das Deutsche Reich.",
    "Wir hatten die erste Polaroid-Kamera – allerdings S/W-Aufnahmen.",
    "Wir hatten Bildtelefon. Da konnte man zu bestimmten Städten telefonieren und sah sein Gegenüber – für 50 Reichspfennige.",
    "Bis auf die Haunebu I, die war nur zu 60% Weltall-tauglich, nebenbei bemerkt.",
    "Flugscheiben mit non-konventionellen Antrieben, Elektrogravitation und Gravitationsabschirmung und Überlichteffekt.",
    "Wissenschaftlich, technologisch war das Deutsche Reich den Alliierten um mindestens 100 Jahre voraus, (...) moralisch um 1.000 Jahre voraus.",
    "Wir haben versucht Quetschmetall aus den Vril-Werkstätten zum schmelzen zu bringen.",
    "Quetschmetall auch wurde verwendet für Plasma-Antrieben von reichsdeutschen Flugscheiben.",
    "Die starteten die Vril-Flugscheiben aus sogenannten spezial-gehärteten Silos.",
    "Ich weiß auch mittlerweile auch, wo die Vril Odin hingestartet ist - zum Aldebaran.",
    "Das muss man natürlich alles wissen, alles das was reichsdeutsche Hochtechnologie vermag.",
    "Heute ist Deutschland ein Entwicklungsland.",
    "Wird sind die fünfte Wurzelrasse, die arische.",
    "Was wir haben, die himmlischen Flugscharen, ne?",
    "Die weiße Rasse stammt vom Aldebaran, vergesst das nicht!",
    "Die erste Wurzelrasse war die Polarrasse.",
    "Das äußerliche dieser Wesenheiten ist uns völlig schleierhaft, (..) Medusen, was weiß ich.",
    "Alles, auch das Universum, ist rhythmisch, zyklisch aufgebaut.",
    "Die Velociraptoren (…) hatte eine eigene Sprache, aus denen entstammen vermutlich die Reptos, iss so.",
    "Die sind nicht weg, die haben sich ins Erdinnere verkrochen.",
    "Da findet man auch Skelette von 8 Metern Länge, humanoid und andere Sachen... Flugscheiben Virmanas und dergleichen mehr.",
    "Woher die Reptos kommen ist mir auch bekannt.",
    "Die Reptos auch, die haben sich nur unterirdisch verlagert durch den Einschlag.",
    "In der Kruste! Nicht die innere Hohlwelt! Das ist ein großer Unterschied!",
    "Reste vom atlantischen Empire – das atlantische Imperium.",
    "Kontinent Mu – die Südhemisphäre.",
    "Dann folgt nach der Polarrasse, die hyperboreische Rasse, auch auf die Nordhemisphäre beschränkt.",
    "Dann, (...) die haben mit uns Ähnlichkeit, die lemurische Rasse.",
    "Nach der lemurischen Rasse, folgte das atlantische Imperium.",
    "Demnach ist die weiße Rasse, also sprich atlantische Imperium, eine Kolonie, eine aldebaranische Kolonie.",
    "Woher sollen die Rassen, Negroid und Asiatit herkommen oder Isaac Krummburg?!",
    "Die ursprünglichen Wesenheiten waren die Reptos, die ich persönlich sehr mag.",
    "Verbotene Archäologie, das sind insgesamt drei Teile.",
    "Gedanken sind infometrische Felder.",
    "Ja, das ist freie Energie.",
    "Zigfache Überlichtgeschwindigkeit - ganz wichtig.",
    "Denn die Erde ist ein lebender Organismus, vergesst das nicht.",
    "Damit haben Sie die Eigenschaft die Zeit der Zellen quasi zurückzudrehen.",
    "Man steckt erst richtig drin, wenn man auch der letzten Klofrau erklären kann, was Zeitreisen sind.",
    "Levitation! Mein Gott, die indischen Gurus machen uns das vor.",
    "Macht es subversiv, geht damit nicht an die Öffentlichkeit, schon garnicht ins Internet.",
    "Wir sprechen von infometrischen Feldern.",
    "Skalarwellen oder Teslawellen sind eigentlich Wellen des Raum-Zeit-Kontinuums.",
    "Die Erdkruste ist ja weltweit ein Gangsystem.",
    "Die Erdkruste … Dort leben ja mehrere Zivilisationen, nicht nur eine. Ich hab Karten darüber.",
    "Eine Million Reichsdeutsche leben dort unten, in der inneren Hohlwelt.",
    "Die altindischen Vimanas! Vimanas heißt Fluggerät Sanskrit, flogen mit Quecksilberwirbelmotoren.",
    "Ich erinnere noch einmal daran, dass mindestens rund eine Million reichsdeutscher Patente in alliierte Hände verschwand!",
    "Apropos unterirdische Bauwerke: Das Verhältnis von oberirdisch zu unterirdisch ist 1 zu 4!",
    "Gesamtberlin, wissen auch die wenigsten: 4 mal mehr - Unterdirdisch! Alles verzweigt!",
    "Daher die vielen Rassen, die unmöglich alle von dieser Erde stammen können.",
    "Anschliessend wurde die Erde als Strafkolonie genutzt.",
    "Unser Universum ist ja ein Perpetuum Mobile.",
    "Die Geheimbasen des Deutschen Reichs haben auch den Wiederaufbau Westdeutschlands organisiert.",
    "Ich sage nur Bipolarität des Universums.",
    "Was macht die Sonne uns vor, Implosion.",
    "Die Sonne ist kalt!",
    "Die Erde ist ja hohl.",
    "Das ist keine mongolische Mikroelektronik sondern deutsche Hochtechnologie!",
    "Ich kann mich in sekundenschnelle mit anderen Sternensystemen, Galaxien informieren.",
    "Das nächste Treffen findet an Führers Geburtstag statt.",
    "Und die sind zum Pluto, dem erdfernsten Planeten gestartet.",
    "Übrigens, meine Energiegruppe hat auch Kontakt zur Dritten Macht.",
    "Um in die innere Hohlwelt zu gelangen, muss ich 4000 KM Gesteinsmaterial überwinden.",
    "Hatten wir auch schon im 3. Reich.",
    "Ein versteckter Hinweis, dass der Mond in reichsdeutscher Hand nämlich ist.",
    "Während des dritten Reiches war Nicola Tesla hier zu Besuch.",
    "Ich nehme auch an, dass da auch das galaktische Imperium Aldebaran eine wesentliche Rolle spielt.",
    "Wir dürfen nicht mit irdischen Maßnahmen herangehen Leute, vergesst das nicht!",
    "Flugscheibenkonstrukteur!",
    "Deutsche Raumfahrt ab 1934.",
    "Das hier ist nichts anderes als ein Strafplanet.",
    "Grüße aus der 9. Milchstraße.",
    "Es gibt eine Art galaktischer Konföderation in unserer Galaxis.",


    # Waffen, Tod, Vernichtung und Gewaltfantasien
    "Liegt im Krankenhaus, ich nehm an, dass sie ihn da mit Mikrowelle traktiert haben.",
    "Strahlenwaffen.. ist schon intelligenter, Mikrowelle, Skalarwelle.",
    "Wenn ich jetzt an Yellowstonepark denke, kann bald passieren, herrlich! Ich liebe ja Katastrophen.",
    "Ich finde Erdbeben schön.",
    "Wenn sich Risse auftun, ganze PKWs versinken, hehe – herrlich!",
    "Was richtet Luft an? Tornados!",
    "Was ist denn da wieder los? Wo ist meine Panzerfaust?",
    "Internet ist ne schöne Waffe.",
    "Jetzt kommen wir zur Wetterbeeinflussung und -kriegsführung durch Skalarwellen.",
    "Tödliche Organwellen.",
    "In Russland nennt man das heute die skalara Haubitze.",
    "Die sehr gefährliche amerikanische Lanzenviper (...) und der Mensch stirbt elendig innerhalb von 20 Minuten.",
    "Mögen sie in ihrem eigenen Blut erSAUFEN!",
    "So schön Waffen sind - es hat keine Sinn, Gewalt mit Gewalt zu begegnen.",
    "Übrigens, Spannung... Millionen von Volt - um das mal zu verdeutlichen!",
    "Und dann Himmel, Arsch und Zwirn!",
    "Die Russen verfügen über Monsterbomben.",
    "Nun wisst ihr auch, wie man künstlich Erdbeben auslöst.",
    "Solche seltenen Wetter-Skalar-Interferometer könnten Kugelblitze produzieren.",
    "Haarp-Projekt Alaska und anderes lässt grüßen.",
    "WAFFENSYSTEME! Da wirds interessant!",
    "Ich weiß auch, wie man sowas bauen kann - Mikrowellenterror und dergleichen mehr.",
    "Bis auf 200 Meter tief und mehr werden alle Hohlräume ausradiert.",
    "Da brauche ich keine Nuklearwaffen - nichtmal Mikrowelle.",
    "Oder ich lass die Fackelmänner los!",
    "Vulkanausbrüche - was Schönes!",
    "Todesstrahlen, Todesstrahlen!",
    "Nuklear oder nicht-nuklear ist egal. Hauptsache alles ist zerstört.",
    "Es hat überhaupt keinen Sinn - der Tod überrascht Jeden!",
    "Zisch - Aus, weg war det - ein schöner Tod.",
    "Von wegen das Märchen über die desolate russische Armee - da kann ich nur lachen!",
    "Heute werden wir über HAARP, sprich Wetterkriegsführung sprechen.",
    "Die Sowjets gackern nicht bevor das Ei gelegt ist.",
    "Man kann davon ausgehen, dass in jedem Neubaublock einer mit Mikrowelle experimentiert.",
    "Gegen Skalarwellen haben sie die Arschkarte - also die goldene.",
    "Nach Möglichkeit mit wenig Blutvergiessen, vergesst das bitte nicht!",
    "Dabei denke ich an die Allee der Gehenkten.",
    "Ich kann aber auch, im Rahmen der Wetterkriegsführung Tornados künstlich erzeugen.",
    "Mikrowellenstrahler!",
    "Ne schöne Waffe, sollte man mal gegen die Loveparade einsetzen.",

    # Gesellschaftskritik
    "Letztlich war er aber nur eine zweibeinige Ertragsmaschine – man muss das mal so knallhart sagen.",
    "Die Wende war nicht plötzlich, die wurde schon von den Zionisten 1899 geplant – von den Illuminaten.",
    "Westliche Wertegemeinschaft und Demokratie sind auch aus meinem Wortschatz GE-STRI-CHEN!",
    "Viele Frauen, die machen da Channeling und da kommt nur elektro-magnetischer Müll herüber.",
    "Fußball... Gotteswillen - Opium fürs Volk saggich nur. Brot und Spiele. Iss was für Bekloppte.",
    "Das deutsche Volk verblödet – da gibt es ein Buch im Kopp-Verlag glaubich.",
    "Denken Sie zum Beispiel an die pervertierten Loveparade-Diskotheken und vieles mehr.",
    "Wer die Lüge kennt und trotzdem nichts unternimmt, macht sich mitschuldig.",
    "Wir werden verfolgt, vernichtet – von Isaak Krummbold.",
    "Es gibt noch andere bösartige Elemente, subversive Elemente – Volksschädlinge!",
    "Und der wurde vom Finanzjudentum auch nur ausgenutzt.",
    "Besser ist immer der persönliche Kontakt, statt da den Elektrojuden zu nutzen.",
    "Internet ist so viel Schrott",
    "Ja aus´n Negern! (…) Aus Schwarz wird nicht weiß!",
    "Die ganzen Darwinismus-Lügen.. vergesst es!",
    "Eins ist aber jeden Fall ist Fakt, dass gewisse Kräfte versuchen die Rechte Szene (…) auseinanderzuplautzen.",
    "Bei Freimaurern, Illuminaten sagen wir mal (...) hat das alles eine Bedeutung.",
    "Wenn man einmal in den Fängen der Ärzte ist, dann hat man verloren.",
    "Energielobby, da ham was wieder, hähä!",
    "Wer GEZ zahlt ist selber dämlich.",
    "Geht mal ins Internet, Google-Suchmaschine, und gebt den Begriff Skalarwellen ein.",
    "Die würden bei mir alle in Physik die Note 100 kriegen.",
    "Die armen Kinder, was aus denen werden soll - ja Mutanten, da hab ich auch kein Mitleid mehr!",
    "Bazillus Dummheit sag ich nur.",
    "Wisst Ihr eigentlich, wie die Dekadenz programmiert ist?",
    "Wir leben in einer virtuellen Scheinwelt.",
    "Ein dummes Volk lässt sich leichter beherrschen.",
    "Facebook, das ist alles was für Psychopathen meiner Meinung nach.",
    "Genau das haben die meisten nicht begriffen. Na ja, was soll man von Mutanten erwarten?",
    "Eine Welt voller Mutanten und Zombies mit einem IQ geringer als eine Dillgurke.",
    "Sie müssen schon Ihren Kopf jetzt zum Denken benutzen und nicht als Hutständer!",
    "Für mich ist das der Elektro-Jude.",
    "Und da braucht man sich nicht zu wundern, über die vielen Mutanten, die rumlaufen.",
    "Es rollen sich mir die Fussnägel auf, wenn ich ins Internet gehe und gucke unter Skalarwelle.",
    "Mindcontrol, Bewusstseinskontrolle, versklavte Gehirne und so weiter und so fort.",
    "Unsinnige Talkshows, wenn ich das schon sehe - Uääääh!",
    "Handy an die Wand schmeissen, weg damit!",

    #Eigenlob und Überheblichkeit
    "Wenn ich meine bisheriges Leben betrachte, dann stelle ich fest, dass es Höhen und Tiefen gab.",
    "Ich muss auch dazu sagen, ich bin auch Sternbild Skorpion – da gibt es keine Grauzonen, nur Schwarz oder Weiß.",
    "Mein nächstes Buch ist auch schon fertig: Die schwarze Macht.",
    "Ich hab auch nur für die Fächer was getan, die mich interessiert haben – gab dann nur Einsen oder Dreien.",
    "Ab meinem 14 Lebensjahr verfügte ich bereits über eine beachtliche geologische und gestaltete an Schulen entsprechende Ausstellungen, welche eine hohe Resonanz hatten.",
    "Seit meinem 15. Lebensjahr wohnte ich in der Reichshauptstadt Berlin.",
    "Sämtliche Naturwissenschaften Eins, wie sich das gehört.",
    "Während dieser Zeit besuchte ich zwei Jahre lang die Abendschule, 11. und 12. Klasse, so mal nebenbei.",
    "Da bin ich übrigens auch Mitglied, Prä-Astronautik- Äntschiens Äh... Ästronaut Society, mit Urkunde (...) und leitete die Uranier-Gruppe Astrophysik.",
    "Mein Kampf gegen die Lügen der Alliierten – das war der Grundstein.",
    "Dort war ich kein geringer als Hauptstrahlenschutzbeauftragter für die gesamte ehemalige DDR.",
    "Die ABC-Waffen gingen alle durch meine Hand, also Massenvernichtungswaffen.",
    "Finanzdienstleistungen – alles son Schnullifax, da weiß ich, wie die Verbrecher arbeiten.",
    "Kurz nach der Wende gründete ich die Fachgruppe Rätsel der Erdgeschichte, die sich auch mit Physik und Paläoastronautik beschäftigte.",
    "Eines Tages bekam ich in diesem Zusammenhang Kontakt zum Templerorden, wo ich heute leitend tätig bin.",
    "Durch jenen Verlag, und das ist jetzt ganz wichtig, gelangte ich an Schriften und Videos zum Thema Reichsdeutsche Hochtechnologie.",
    "Ich muss nur dazu sagen, in Naturwissenschaften kenne ich mich überall sehr gut aus, da macht mir so schnell keiner was vor.",
    "Sprache beherrsche ich – mehrere Fremdsprachen, ist für mich aber nur Mittel zum Zweck.",
    "Sportarten guck ich nur das, die ich selbst betrieben habe, bis zur Meisterschaft: Schach, Fechten, Degen, Florett, Schwert, Schießen und Military-Reiten, alles andere kann mich keiner hinterm Ofen vorlocken.",
    "Im erstgenannten Buch, Hochtechnologie im Dritten Reich ,habe ich nicht nur physikalisch, mathematisch reichsdeutsche Technologien beschrieben, sondern räumte auch die hörigen alliierten Lügen gegen das Deutsche Reich auf.",
    "Angst und Unmöglichkeit sind aus meinem Wortschatz gestrichen.",
    "So lange ich lebe wird mein Kampf gegen die Alliierten anhalten.",
    "Napoleon Bonaparte ist auch eines meine Vorbilder, militärisch.",
    "Ich denke ja ganzheitlich vernetzt, nicht wahr!?",
    "Ich habe so viel Chaoten in letzter Zeit kennen gelernt, also... Schade um die Zeit, da hätte ich schon hundert Differentialgleichungen lösen können.",
    "Namen sind für mich Schall und Rauch, für mich sind Zahlen wesentlich.",
    "Ich selber bin die graue Eminenz.",
    "Gerichte und Polizei sind für mich Fremdwörter.",
    "Ich hab den Schutz der Dritten Macht!",
    "Ich genieße den Templerschutz und den Schutz der National Security Eygenzi.",
    "Bei mir in der Energiegruppe, die Leute, die nicht in der Lage sind ein einfaches Integral zu lösen, die schmeiße ich gnadenlos schon raus.",
    "Wenn andere die Fenster putzen (...), da löse ich partielle Differentialgleichungen.",
    "Ich kann Zeit beschleunigen, ich kann Zeit aber auch verlangsamen.",
    "Wir sind die Top-Ten, auf der ganzen Erde.",
    "Ich beherrsche die englische Sprache in Wort, Bild und Schrift.",
    "Man sollte sich mit Putin gut stellen - Ich kenne ihn übrigens persönlich, komme mit ihm gut klar.",
    "Auch nachzulesen in meinem Bestseller-Buch.",
    "Nicht umsonst ist ja eines meiner Bücher ein Bestseller.",
    "Ich sitze auf der Spitze der Pryramide.",

    # Einbeziehung der Teilnehmer
    "Für die Templermitglieder, Bernd? Nächsten Sonnabend, Roseneck – ab 18:00 Uhr, weisse bescheid?",
    "Kevin du beschäftigst dich damit hoffentlich (...) - du, ich frag Dir das ab sonst.",
    "Kevin los, schreib das auf!",

    # Tiere
    "Trilobiten Dreilapp-Krebse, offiziell ausgestorben, hahahaha!",
    "Wenn man seine Katze in den Mikrowellenherd zum Trocknen reinschiebt sieht man die Wirkung am Besten.",
    "Täglich sterben tausende von Tierarten aus.",

    # Störungen und Empfindlichkeiten
    "Was bedeutete die Wende für mich? Zunächst einmal nur Nachteile.",
    "Zu viel Flüssigkeit.. der Regen, der reicht schon.",
    "Wasser ist Gift!",
    "Ich selber bin ein stinkenfauler Mensch was körperliche Arbeit angeht.",
    "Ich bin ein Mensch, wenn ich schon Schnee sehe, kriege ich 'ne Erkaeltung.",
    "Ich hasse Schnee, ist was fuer dumme Bauern.",
    "Meine Temperaturen sind 40 Grad plus und 100% Luftfeuchtigkeit.",
    "Alles was unter 20 Grad ist, ist fuer mich Frost.",
    "Da komme ich mir vor wie eine tibetanische Gebetsmuehle oder tausend Studenten.",

    # Rhetorisches Füllmaterial
    "Es gibt keine Zufälle.",
    "Wir sind nicht umsonst hier hineininkarniert oder hineingeboren.",
    "Hähä!",
    "Muss man wissen!",
    "Silentium!",
    "Ruhe!",

    # Gemischtes
    "Alle 100 Jahre findet ein großer Illuminati-Kongress statt, da werden die Ziele für die nächsten 100 Jahre gesteckt, auch der Euro.",
    "Konfuzius, das ist der Status Quo.",
    "Mindestens sind das reine Vegetarier, was mir schon sympathisch ist.",
    "Übrigens gibt es kein Gut und kein Böse in dem Sinne.",
    "Am besten einen Stiefel Whisky trinken.",
    "Mit Dynamit beginnt man den Tag dynamisch!",
    "Arme und Beine bilden eine rotierende Scheibe, die Ohren flattern im Wind und das Arschloch bildet den höchsten Punkt.",
    "Die lachen uns aus!",
    "Das ist geheimes Templerwissen.",
    "Die Inselaffen hasse ich sowieso!",
    "Rotwein ist gesund - Templerwein!",
    "Alles ist vorhersehbar!",
    "3 mal Storgram reinen Alkohol!",
    "Mein Führersoffizier sagte mir einmal: \"Junge, du kannst dich in der Zeile irren, aber niemals in der Spalte\" Jaja, Spaß muss sein.",

]
